openapi: 3.0.0
info:
  title: Employee_Management_System
  description: API for managing employee records
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/RKEERTHANA2312_1/Empoyee_Management/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/RKEERTHANA2312_1/Employee_Management_System1/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /employees:
    get:
      summary: Retrieve all employees
      responses:
        "200":
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      summary: Create a new employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        "201":
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
  /employees/{id}:
    get:
      summary: Retrieve a specific employee by ID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Employee details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        "404":
          description: Employee not found
    put:
      summary: Update an employee's details
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        "200":
          description: Employee updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        "404":
          description: Employee not found
    delete:
      summary: Delete an employee
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Employee deleted successfully
        "404":
          description: Employee not found
components:
  schemas:
    Employee:
      required:
      - department
      - email
      - name
      - position
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the employee
        name:
          type: string
          description: Name of the employee
        position:
          type: string
          description: Job position of the employee
        department:
          type: string
          description: Department of the employee
        email:
          type: string
          description: Email address of the employee
          format: email
        phone:
          type: string
          description: Phone number of the employee
